### ISSUE TITLE
undefined offset

### ISSUE THREAD

**Issue by liftSpindle** [dwijitsolutions/laraadmin-crm#8]
Hello,

Thank you for making such great software. I am curious about your CRM. I git cloned into /var/www/html and installed with composer. When I use la:install i get a undefined offset. 

I have installed laraadmin many times. I'm pretty sure I have installed the crm before too, on a windows xampp stack.

Did I do something wrong or this is a bug? 

LAInstall::handle exception: ErrorException: Undefined offset: 0 in /var/www/html/vendor/dwij/laraadmin/src/Models/Module.php:725
Stack trace:
#0 /var/www/html/vendor/dwij/laraadmin/src/Models/Module.php(725): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined offse...', '/var/www/html/v...', 725, Array)
#1 /var/www/html/vendor/dwij/laraadmin/src/Models/Module.php(58): Dwij\Laraadmin\Models\Module::format_fields(Array)
#2 /var/www/html/database/migrations/2016_11_16_123515_create_contacts_table.php(22): Dwij\Laraadmin\Models\Module::generate('Contacts', 'contacts', 'first_name', 'fa-user', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(373): CreateContactsTable->up()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(380): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(162): Illuminate\Database\Migrations\Migrator->runMigration(Object(CreateContactsTable), 'up')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(130): Illuminate\Database\Migrations\Migrator->runUp('2016_11_16_1235...', 1, false)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(97): Illuminate\Database\Migrations\Migrator->runMigrationList(Array, Array)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(65): Illuminate\Database\Migrations\Migrator->run(Array, Array)
#9 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#12 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(185): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/RefreshCommand.php(65): Illuminate\Console\Command->call('migrate', Array)
#16 [internal function]: Illuminate\Database\Console\Migrations\RefreshCommand->fire()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#19 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(185): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#22 /var/www/html/vendor/dwij/laraadmin/src/Commands/LAInstall.php(221): Illuminate\Console\Command->call('migrate:refresh')
#23 [internal function]: Dwij\Laraadmin\Commands\LAInstall->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#26 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/vendor/symfony/console/Application.php(820): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/vendor/symfony/console/Application.php(187): Symfony\Component\Console\Application->doRunCommand(Object(Dwij\Laraadmin\Commands\LAInstall), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/html/vendor/symfony/console/Application.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 {main}

  [Exception]
  LAInstall::handle Unable to install : Undefined offset: 0

**Comment by liftSpindle** [comment]
is it necessary to run 

php artisan migrate --seed
php artisan key:generate

after composer install and before la:install
